-- 1. Create Schema
CREATE SCHEMA IF NOT EXISTS tasks;

-- 2. Custom PostgreSQL Enum Types
CREATE TYPE tasks.task_priority AS ENUM ('LOW', 'MEDIUM', 'HIGH');
CREATE TYPE tasks.task_status AS ENUM ('TODO', 'IN_PROGRESS', 'DONE');
CREATE TYPE tasks.user_role AS ENUM ('USER', 'ADMIN');

grant usage on schema tasks to spring_boot_user;

create type task_priority as enum ('LOW', 'MEDIUM', 'HIGH');

create type task_status as enum ('TODO', 'IN_PROGRESS', 'DONE');

create type user_role as enum ('USER', 'ADMIN');

-- 3. Users Table
CREATE TABLE tasks.users (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             username VARCHAR(30) NOT NULL UNIQUE,
                             email VARCHAR(250) NOT NULL UNIQUE,
                             password_hash VARCHAR(255),
                             role tasks.user_role DEFAULT 'USER',
                             created_at TIMESTAMPTZ DEFAULT NOW(),
                             updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tasks Table
CREATE TABLE tasks.tasks (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             user_id BIGINT REFERENCES tasks.users(id) ON DELETE CASCADE,
                             title VARCHAR(120) NOT NULL UNIQUE,
                             description VARCHAR(256),
                             status tasks.task_status DEFAULT 'TODO',
                             priority tasks.task_priority DEFAULT 'MEDIUM',
                             due_date DATE CHECK (due_date >= CURRENT_DATE),
                             created_at TIMESTAMPTZ DEFAULT NOW(),
                             updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Query Performance Indexes
CREATE INDEX idx_tasks_user_id ON tasks.tasks (user_id);
CREATE INDEX idx_tasks_status ON tasks.tasks (status);
CREATE INDEX idx_tasks_due_date ON tasks.tasks (due_date);
