create schema tasks;

alter schema tasks owner to app_admin;

grant usage on schema tasks to spring_boot_user;

create type task_priority as enum ('LOW', 'MEDIUM', 'HIGH');

create type task_status as enum ('TODO', 'IN_PROGRESS', 'DONE');

create type user_role as enum ('USER', 'ADMIN');

CREATE TABLE tasks.users (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             username VARCHAR(30) NOT NULL UNIQUE,
                             email VARCHAR(250) NOT NULL UNIQUE,
                             password_hash VARCHAR(255),
                             role tasks.user_role DEFAULT 'USER',
                             created_at TIMESTAMPTZ DEFAULT NOW(),
                             updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE tasks.tasks (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             user_id BIGINT REFERENCES tasks.users(id) ON DELETE CASCADE,
                             title VARCHAR(120) NOT NULL UNIQUE,
                             description VARCHAR(256),
                             status tasks.task_status DEFAULT 'TODO',
                             priority tasks.task_priority DEFAULT 'MEDIUM',
                             due_date DATE CHECK (due_date >= CURRENT_DATE),
                             created_at TIMESTAMPTZ DEFAULT NOW(),
                             updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 1. Create a reusable trigger function
CREATE OR REPLACE FUNCTION tasks.update_timestamp()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2. Attach trigger to tasks.users
CREATE TRIGGER set_users_updated_at
    BEFORE UPDATE ON tasks.users
               FOR EACH ROW
EXECUTE FUNCTION tasks.update_timestamp();

-- 3. Attach trigger to tasks.tasks
CREATE TRIGGER set_tasks_updated_at
    BEFORE UPDATE ON tasks.tasks
    FOR EACH ROW
EXECUTE FUNCTION tasks.update_timestamp();
