/**
 * ==============================================================================
 * User Entity (JPA Domain Model & Spring Security UserDetails)
 * ==============================================================================
 * This class represents a row in the {@code tasks.users} database table.
 *
 * It serves a dual purpose:
 * 1. <b>JPA Entity</b>: Mapped to the relational database using Hibernate ORM.
 * 2. <b>Spring Security {@link UserDetails}</b>: Acts as the principal object representing
 *    the logged-in user throughout the Spring Security context.
 *
 * <h3>Key Concepts for Beginners:</h3>
 * <ul>
 *   <li><b>ORM (Object-Relational Mapping)</b>:
 *       Hibernate automatically translates Java objects into SQL {@code INSERT},
 *       {@code SELECT}, {@code UPDATE}, and {@code DELETE} statements so you don't
 *       have to write raw JDBC queries manually.</li>
 *
 *   <li><b>Identity Generation ({@code GenerationType.IDENTITY})</b>:
 *       Tells the database engine (e.g. PostgreSQL) to auto-increment the ID column
 *       using a database sequence.</li>
 *
 *   <li><b>Bidirectional One-to-Many Relationship</b>:
 *       One user has many tasks. The {@code mappedBy = "user"} tells Hibernate that the
 *       {@code TaskEntity} class owns the foreign key column ({@code user_id}).</li>
 *
 *   <li><b>Lazy Loading ({@code FetchType.LAZY})</b>:
 *       When you load a user from the database, Hibernate does NOT immediately query the
 *       tasks table. It only queries tasks when you explicitly call {@code user.getTasks()}.
 *       This prevents loading thousands of unneeded records into memory.</li>
 * </ul>
 * ==============================================================================
 */
package info.jeffkerns.taskmanager.entity;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

@Entity
@Table(name = "users", schema = "tasks")
public class UserEntity implements UserDetails {

    /**
     * Primary Key identifier.
     * Auto-generated by the database identity/sequence on insertion.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique username for login (max 30 characters).
     */
    @Column(name = "username", nullable = false, unique = true, length = 30)
    private String username;

    /**
     * Unique email address for notifications and identification (max 250 characters).
     */
    @Column(name = "email", nullable = false, unique = true, length = 250)
    private String email;

    /**
     * Salted BCrypt password hash.
     * NEVER store plain-text passwords in this field!
     */
    @Column(name = "password_hash", length = 255)
    private String passwordHash;

    /**
     * User's system role (e.g. USER, ADMIN).
     * {@code @JdbcTypeCode(SqlTypes.NAMED_ENUM)} tells Hibernate to map this Java enum
     * to PostgreSQL's native {@code tasks.user_role} custom enum type.
     */
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "role", nullable = false, columnDefinition = "tasks.user_role")
    private UserRole role = UserRole.USER;

    /**
     * All tasks owned by this user.
     * <ul>
     *   <li>{@code cascade = CascadeType.ALL}: If a user is deleted, their tasks are also deleted.</li>
     *   <li>{@code orphanRemoval = true}: If a task is removed from this list, delete it from the DB.</li>
     *   <li>{@code fetch = FetchType.LAZY}: Only load tasks when accessed.</li>
     * </ul>
     */
    @OneToMany(
        mappedBy = "user",
        cascade = CascadeType.ALL,
        orphanRemoval = true,
        fetch = FetchType.LAZY
    )
    private List<TaskEntity> tasks = new ArrayList<>();

    /**
     * Timestamp when the user record was initially created.
     * {@code updatable = false} ensures Hibernate will never include this column in UPDATE statements.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Timestamp when the user record was last modified.
     */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * Default no-argument constructor required by JPA specification.
     * Protected visibility prevents direct instantiation without initial values while
     * still allowing Hibernate to create instances via reflection.
     */
    protected UserEntity() {}

    /**
     * Convenience constructor for creating a new user instance before persisting.
     *
     * @param username     the user's unique username
     * @param email        the user's email address
     * @param passwordHash the BCrypt-hashed password
     * @param role         the user's assigned security role
     */
    public UserEntity(String username, String email, String passwordHash, UserRole role) {
        this.username = username;
        this.email = email;
        this.passwordHash = passwordHash;
        this.role = role != null ? role : UserRole.USER;
    }

    /**
     * Lifecycle callback executed automatically by JPA just before the entity is first persisted (INSERT).
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = Instant.now();
        this.updatedAt = Instant.now();
    }

    /**
     * Lifecycle callback executed automatically by JPA just before an existing entity is updated (UPDATE).
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Synchronizes bidirectional relationship when adding a task to this user.
     * Keeps the in-memory object graph consistent with the database state.
     *
     * @param task the task to associate with this user
     */
    public void addTask(TaskEntity task) {
        tasks.add(task);
        task.setUser(this);
    }

    /**
     * Synchronizes bidirectional relationship when removing a task from this user.
     *
     * @param task the task to disassociate
     */
    public void removeTask(TaskEntity task) {
        tasks.remove(task);
        task.setUser(null);
    }

    // =========================================================================
    // Spring Security UserDetails Contract Methods
    // =========================================================================

    /**
     * Returns the authorities (roles/permissions) granted to this user.
     * Spring Security checks these during authorization (e.g. {@code @PreAuthorize("hasRole('ADMIN')")}).
     *
     * @return a list containing the user's role wrapped in {@link SimpleGrantedAuthority}
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return List.of(new SimpleGrantedAuthority(role.getAuthority()));
    }

    /**
     * Returns the password used to authenticate the user.
     *
     * @return the BCrypt-hashed password string
     */
    @Override
    public String getPassword() {
        return passwordHash;
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return the username string
     */
    @Override
    public String getUsername() {
        return username;
    }

    /** Indicates whether the user's account has expired. (Always active here) */
    @Override
    public boolean isAccountNonExpired() { return true; }

    /** Indicates whether the user is locked or unlocked. (Always unlocked here) */
    @Override
    public boolean isAccountNonLocked() { return true; }

    /** Indicates whether the user's credentials (password) have expired. */
    @Override
    public boolean isCredentialsNonExpired() { return true; }

    /** Indicates whether the user is enabled or disabled. */
    @Override
    public boolean isEnabled() { return true; }

    // =========================================================================
    // Standard Getters and Setters
    // =========================================================================

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public void setUsername(String username) { this.username = username; }
    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }
    public String getPasswordHash() { return passwordHash; }
    public void setPasswordHash(String passwordHash) { this.passwordHash = passwordHash; }
    public UserRole getRole() { return role; }
    public void setRole(UserRole role) { this.role = role; }
    public List<TaskEntity> getTasks() { return tasks; }
    public Instant getCreatedAt() { return createdAt; }
    public Instant getUpdatedAt() { return updatedAt; }

    /**
     * Compares entities based on primary key identity.
     *
     * <p><b>Beginner Tip:</b> In JPA, two entity objects represent the same database row
     * if they have the same non-null primary key ID.</p>
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UserEntity other)) return false;
        return id != null && id.equals(other.id);
    }

    /**
     * Returns a constant hash code for entities to comply with JPA and Hibernate set/map semantics.
     */
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
